name: minecraft_chatbot
version: 1.0
main: com.github.isaidthat.MinecraftChatbot
api-version: 1.21

commands:
  chat:
    description: talk to an llm
    usage: /chat <prompt>
  
  model:
    description: set model
    usage: /model <model name>

  apikey:
    description: set api key
    usage: /token <your api key>

permissions:
  bot.chat:
    description: allows using chatbot commands
    default: op